# Generated by Django 4.0.2 on 2022-02-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cateory',
            new_name='category',
        ),
    ]
