# Generated by Django 4.0.2 on 2022-03-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_nome_category_name'),
        ('project', '0002_rename_cateory_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='category.category'),
        ),
    ]
